version: '3.8'

services:
  flask:
    # image: my-flask-app:v1
    build: .
    restart: always
    container_name: flask
    ports:
      - 8000:5000
    volumes:
      - ~/dev/hmh/docker-course:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    networks:
      - backend

  db:
    image: mysql:5.7
    container_name: db 
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
        - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: course
    networks:
      - backend
networks:
    backend: